---
# tasks file for zoneminder


- name: Install Zoneminder Repository
  block:
    - name: zoneminder | apt key
      ansible.builtin.get_url:
        url: https://zmrepo.zoneminder.com/debian/archive-keyring.gpg
        dest: /etc/apt/trusted.gpg.d/zoneminder.asc

    - name: zoneminder | apt source
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/zoneminder.asc] https://zmrepo.zoneminder.com/debian/release-1.36 {{ zoneminder_debrelease }}/"
        state: present
        update_cache: true
  tags:
    - install

- name: Install packages for zoneminder
  ansible.builtin.apt:
    pkg:
      - lsb-release
      - gnupg2
      - zoneminder=1.36.31-bullseye1
  tags:
    - install

- name: Enable Authentication in zoneminder
  ansible.builtin.copy:
    dest: /etc/zm/conf.d/03-custom.conf
    content: "ZM_OPT_USE_AUTH=1"
    mode: "0644"

- name: Set admin password
  ansible.builtin.shell:
    cmd: mysql -e "UPDATE Users set Password=PASSWORD('{{zoneminder_admin_pw}}') WHERE Username='admin'" zm && echo 1 > /root/.zm_pw_change
    creates: /root/.zm_pw_change

- name: Enable zoneminder service
  ansible.builtin.service:
    name: zoneminder
    enabled: yes
    state: started
  tags:
    - config
    - service

- name: Enable zoneminder apache-config
  ansible.builtin.file:
    dest: /etc/apache2/conf-enabled/zoneminder.conf
    src: /etc/apache2/conf-available/zoneminder.conf
    state: link
  tags:
    - config
    - http
  notify: apache-restart

- name: Register cameras
  community.mysql.mysql_query:
    login_db: zm
    query:
      - INSERT INTO Monitors (`Id`, `Name`, `Notes`, `ServerId`, `StorageId`, `Type`, `Function`, `Enabled`, `DecodingEnabled`, `LinkedMonitors`, `Triggers`, `ONVIF_URL`, `ONVIF_Username`, `ONVIF_Password`, `ONVIF_Options`, `Device`, `Channel`, `Format`, `V4LMultiBuffer`, `V4LCapturesPerFrame`, `Protocol`, `Method`, `Host`, `Port`, `SubPath`, `Path`, `SecondPath`, `Options`, `User`, `Pass`, `Width`, `Height`, `Colours`, `Palette`, `Orientation`, `Deinterlacing`, `DecoderHWAccelName`, `DecoderHWAccelDevice`, `SaveJPEGs`, `VideoWriter`, `OutputCodec`, `Encoder`, `OutputContainer`, `EncoderParameters`, `RecordAudio`, `RTSPDescribe`, `Brightness`, `Contrast`, `Hue`, `Colour`, `EventPrefix`, `LabelFormat`, `LabelX`, `LabelY`, `LabelSize`, `ImageBufferCount`, `MaxImageBufferCount`, `WarmupCount`, `PreEventCount`, `PostEventCount`, `StreamReplayBuffer`, `AlarmFrameCount`, `SectionLength`, `MinSectionLength`, `FrameSkip`, `MotionFrameSkip`, `AnalysisFPSLimit`, `AnalysisUpdateDelay`, `MaxFPS`, `AlarmMaxFPS`, `FPSReportInterval`, `RefBlendPerc`, `AlarmRefBlendPerc`, `Controllable`, `ControlId`, `ControlDevice`, `ControlAddress`, `AutoStopTimeout`, `TrackMotion`, `TrackDelay`, `ReturnLocation`, `ReturnDelay`, `ModectDuringPTZ`, `DefaultRate`, `DefaultScale`, `SignalCheckPoints`, `SignalCheckColour`, `WebColour`, `Exif`, `Sequence`, `ZoneCount`, `Refresh`, `DefaultCodec`, `Latitude`, `Longitude`, `RTSPServer`, `RTSPStreamName`, `Importance`) VALUES (%(cam_id)s, %(cam_name)s, '', '0', '0', 'Ffmpeg', 'Monitor', '1', '1', NULL, '', '', '', '', '', '', '0', '0', NULL, '1', NULL, 'rtpRtsp', NULL, '', '', %(cam_url)s, NULL, NULL, NULL, NULL, %(cam_width)s, %(cam_height)s, '4', '0', 'ROTATE_0', '0', NULL, NULL, '3', '0', '0', 'auto', NULL, '\# Lines beginning with \# are a comment \r\n\# For changing quality, use the crf option\r\n\# 1 is best, 51 is worst quality\r\ncrf=23', '0', '0', '-1', '-1', '-1', '-1', 'Event-', %(cam_labelformat)s, '0', '0', '1', '3', '0', '0', '5', '5', '0', '1', '600', '10', '0', '0', NULL, '0', NULL, NULL, '100', '6', '6', '0', NULL, NULL, 'user:port@ip', NULL, '0', NULL, '-1', NULL, '0', '100', '0', '0', '#0000be', '#425fed', '0', '1', '0', NULL, 'auto', NULL, NULL, '0', '', 'Normal')
      - INSERT INTO Zones SET MonitorId = %(cam_id)s, Name = 'All', Type = 'Active', Units = 'Percent', NumCoords = 4, Coords = '0,0 1919,0 1919,1079 0,1079', Area='2073600', AlarmRGB = 0xff0000, CheckMethod = 'Blobs', MinPixelThreshold = 25, MinAlarmPixels='62208', MaxAlarmPixels='1555200', FilterX = 3, FilterY = 3, MinFilterPixels='62208', MaxFilterPixels='1555200', MinBlobPixels='41472', MinBlobs = 1;
    single_transaction: true
    named_args:
      cam_url: '{{ item.url }}'
      cam_id: "{{ item.id }}"
      cam_name: "{{ item.name }}"
      cam_width: "{{ item.width | default('1920') }}"
      cam_height: '1080'
      cam_labelformat: '%N - %d/%m/%y %H:%M:%S'
  with_items: "{{ zoneminder_cams }}"
  tags:
    - cams
